language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
  - coverage run run_tests.py

after_success:
  - codecov